[tunnel] Public URL: https://varo-rebilling.loca.lt
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:34023 (check your firewall settings)
    at Socket.<anonymous> (/Users/michaellackner/another try/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
Emitted 'error' event on Tunnel instance at:
    at TunnelCluster.<anonymous> (/Users/michaellackner/another try/node_modules/localtunnel/lib/Tunnel.js:96:12)
    at TunnelCluster.emit (node:events:519:28)
    at Socket.<anonymous> (/Users/michaellackner/another try/node_modules/localtunnel/lib/TunnelCluster.js:50:14)
    at Socket.emit (node:events:519:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.19.0
